apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: churn-api
  namespace: churn-mlops
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: churn-api
  namespaceSelector:
    matchNames:
      - churn-mlops
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
