resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - batch-cronjob.yaml
  - drift-cronjob.yaml
  - retrain-cronjob.yaml
  - batch-score-proxy-cronjob.yaml
  - seed-model-job.yaml
