resources:
  - plain/namespace.yaml
  - plain/pvc.yaml
  - plain/configmap.yaml
  - plain/api-deployment.yaml
  - plain/api-service.yaml
  - plain/batch-score-proxy-cronjob.yaml
  - plain/seed-model-job.yaml
  - batch-cronjob.yaml
  - drift-cronjob.yaml
  - retrain-cronjob.yaml
