apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - batch-cronjob.yaml
  - drift-cronjob.yaml
  - drift-auto-retrain-cronjob.yaml
  - high-drift-cronjob.yaml
  - retrain-cronjob.yaml
  - batch-score-proxy-cronjob.yaml
  - seed-model-job.yaml
  # - monitoring/servicemonitor.yaml
  # - monitoring/prometheus-rules.yaml
