apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: churn-mlops

resources:
  - configmap.yaml
  - secret-example.yaml
  - pvc.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
