apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  annotations:
    # After Terraform apply, set to the output "mlflow_irsa_role_arn"
    # eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/churn-mlops-mlflow-s3
