apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "churn-mlops.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get "config/config.yaml" | indent 4 }}
